
INSERT INTO PERFIL (id, nome) VALUES (1, 'INTERNO');
INSERT INTO PERFIL (id, nome) VALUES (2, 'EXTERNO');


-- Perfil EXTERNO
INSERT INTO PERFIL_PERMISSAO (perfil_id, permissao) VALUES (2, 'EMPRESA_CADASTRO');
INSERT INTO PERFIL_PERMISSAO (perfil_id, permissao) VALUES (2, 'EMPRESA_LISTA');

-- Perfil INTERNO
INSERT INTO PERFIL_PERMISSAO (perfil_id, permissao) VALUES (1, 'EMPRESA_CADASTRO');
INSERT INTO PERFIL_PERMISSAO (perfil_id, permissao) VALUES (1, 'EMPRESA_LISTA');
INSERT INTO PERFIL_PERMISSAO (perfil_id, permissao) VALUES (1, 'EMPRESA_EDICAO');
INSERT INTO PERFIL_PERMISSAO (perfil_id, permissao) VALUES (1, 'EMPRESA_MASTER');

-- USUARIOS
INSERT INTO USUARIO (id, nome, certificado, perfil_id)
VALUES (1, 'Usuario Interno', 'CERT-INT-001', 1);

INSERT INTO USUARIO (id, nome, certificado, perfil_id)
VALUES (2, 'Usuario Externo 1', 'CERT-EXT-001', 2);


ALTER TABLE PERFIL ALTER COLUMN id RESTART WITH 10;
ALTER TABLE USUARIO ALTER COLUMN id RESTART WITH 10;